config/routes.rb
Rails.application.routes.draw do
	root "dashboard#index"

	get "dashboard" => "dashboard#index"
	get "index" => "dashboard#index"
	get "dashboard/index" => "dashboard#index"
	#get 'welcome/index'

	#insert member in a team
	post "/dashboard/teams/:id/insert_member/" => "member_teams#insert_member", as: "insert_member_team"
	get "/dashboard/teams/:id/insert_member/" => "member_teams#insert_member_page", as: "insert_member"

	#delete member of a team
	patch "/dashboard/teams/:id/unsubscribe/:id_subscribe" => "member_teams#unsubscribe_member", as: "unsubscribe_member"

	#former members
	get "/dashboard/teams/:id/former_members/" => "member_teams#former_members", as: "former_members"

	devise_for :users
	resources :members, path: '/dashboard/members'
	resources :teams, path: '/dashboard/teams'
	resources :icm_events, path: '/dashboard/icm_events'
	resources :churches, path: '/dashboard/churches'
end

app/models/icm_event.rb
class IcmEvent < ApplicationRecord
end

app/controllers/icm_events_controller.rb
class IcmEventsController < ApplicationController
  before_action :set_icm_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /icm_events
  # GET /icm_events.json
  def index
    @icm_events = IcmEvent.all
    @title_section = "Eventos"
    @title = @title_section
  end

  # GET /icm_events/1
  # GET /icm_events/1.json
  def show
    @title_section = @icm_event.name
    @title = "Tipo: " + @title_section
  end

  # GET /icm_events/new
  def new
    @icm_event = IcmEvent.new
    @title_section = "Cadastro de Evento"
    @title = @title_section
  end

  # GET /icm_events/1/edit
  def edit
    @title_section = "Editando: " + @icm_event.name
    @title = @title_section
  end

  # POST /icm_events
  # POST /icm_events.json
  def create
    @icm_event = IcmEvent.new(icm_event_params)

    respond_to do |format|
      if @icm_event.save
        format.html { redirect_to @icm_event, notice: 'Icm event was successfully created.' }
        format.json { render :show, status: :created, location: @icm_event }
      else
        format.html { render :new }
        format.json { render json: @icm_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /icm_events/1
  # PATCH/PUT /icm_events/1.json
  def update
    respond_to do |format|
      if @icm_event.update(icm_event_params)
        format.html { redirect_to @icm_event, notice: 'Icm event was successfully updated.' }
        format.json { render :show, status: :ok, location: @icm_event }
      else
        format.html { render :edit }
        format.json { render json: @icm_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /icm_events/1
  # DELETE /icm_events/1.json
  def destroy
    @icm_event.destroy
    respond_to do |format|
      format.html { redirect_to icm_events_url, notice: 'Icm event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_icm_event
      @icm_event = IcmEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def icm_event_params
      params.require(:icm_event).permit(:name, :description, :event_date, :limit_reg)
    end
end

app/helpers/icm_events_helper.rb
module IcmEventsHelper
end

app/views/icm_events/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
          Insira dos Dados Corretamente
      </div>                
      <div class="panel-body">
        <div class="row">
          <%= form_with(model: icm_event, local: true) do |form| %>
            <% if icm_event.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(icm_event.errors.count, "error") %> prohibited this icm_event from being saved:</h2>

                <ul>
                <% icm_event.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="col-lg-6">                                
              <div class="form-group">
                <%= form.label "Nome" %>
                <%= form.text_field :name, id: :icm_event_name, class: "form-control", placeholder: "Insira o Nome" %>
              </div>                                
            </div> <!-- col-lg-6 -->
            <div class="col-lg-6">                                
              <div class="form-group">
                <%= form.label "Descrição" %>
                <%= form.text_field :description, id: :icm_event_description, class: "form-control", placeholder: "Insira a Descrição" %>
              </div>                                
            </div> <!-- col-lg-6 -->


            <div class="col-lg-6">
              <div class="form-group">
                <%= form.label "Data do Evento" %>
                <%= form.date_select :event_date, id: :icm_event_event_date, :order => [:day, :month, :year], start_year: 2018, :class => "form-control" %>
              </div>
            </div> <!-- col-lg-6 -->
            <div class="col-lg-6">
              <div class="form-group">
                <%= form.label "Fechamento das Inscrições" %>
                <%= form.date_select(:limit_reg, id: :icm_event_limit_reg, :order => [:day, :month, :year], start_year: 2018, :class => "form-control") %>
              </div>
            </div> <!-- col-lg-6 -->

            <div class="col-lg-12">
              <%= form.submit "Finalizar", class: "btn btn-default" %>
              <%= link_to 'Voltar', icm_events_path, class: "btn btn-default" %>
            </div>
          <% end %>
          <%#= link_to 'Voltar', churches_path, class: "btn btn-default" %>
        </div> <!-- row -->
      </div> <!-- panel-body -->
    </div> <!-- panel panel-default -->
  </div> <!-- col-lg-12 -->
</div> <!-- row -->

app/views/icm_events/edit.html.erb
<%= render 'form', icm_event: @icm_event %>

<%#= link_to 'Show', @icm_event %>
<%#= link_to 'Back', icm_events_path %>

app/views/icm_events/index.html.erb
<%#<p id="notice"><%= notice </p>%>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
          Listagem
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
          <thead>
            <tr>
              <th>Nome</th>
              <th><center>Data do Evento</center></th>
              <th><center>Fechamento</center></th>
              <th><center>Ações</center></th>
            </tr>
          </thead>

          <tbody>
            <% @icm_events.each do |icm_event| %>
              <tr>
                <td><%= icm_event.name %></td>
                <td><center><%= icm_event.event_date %></center></td>
                <td><center><%= icm_event.limit_reg %></center></td>
                <td>
                  <center>
                    <%= link_to 'Exibir', icm_event %> | 
                    <%= link_to 'Editar', edit_icm_event_path(icm_event) %> |
                    <%= link_to 'Excluir', icm_event, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </center>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%#= link_to 'New User Type', new_user_type_path %>
      </div><!-- /.panel-body -->      
    </div><!-- /.panel -->    
  </div><!-- /.col-lg-12 -->  
</div><!-- row -->

app/views/icm_events/new.html.erb
<%= render 'form', icm_event: @icm_event %>

<%#= link_to 'Back', icm_events_path %>

app/views/icm_events/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Dados Completos <%#Outros Dados%>
      </div>                
      <div class="panel-body">
        <div class="row">
          <% if (notice) %>
            <div class="col-lg-12">
            	<div class="alert alert-success">
			      <%= notice %>
            	</div>          	
            </div>
          <% end %>
          <div class="col-lg-12">
			<p> <b>Descrição:</b> <%= @icm_event.description %> </p>
			<p> <b>Data do Evento:</b> <%= @icm_event.event_date %> </p>
			<p> <b>Fechamento:</b> <%= @icm_event.limit_reg %> </p>

			<hr>

			<%= link_to 'Edit', edit_icm_event_path(@icm_event), class: "btn btn-default" %>
			<%= link_to 'Back', icm_events_path, class: "btn btn-default" %>
          </div> <!-- col-lg-12 -->
        </div> <!-- row -->
      </div> <!-- panel-body -->
    </div> <!-- panel panel-default -->
  </div> <!-- col-lg-12 -->
</div> <!-- row -->    