config/routes.rb
Rails.application.routes.draw do
	root "dashboard#index"

	get "dashboard" => "dashboard#index"
	get "index" => "dashboard#index"
	get "dashboard/index" => "dashboard#index"
	#get 'welcome/index'

	#insert member in a team
	post "/dashboard/teams/:id/insert_member/" => "member_teams#insert_member", as: "insert_member_team"
	get "/dashboard/teams/:id/insert_member/" => "member_teams#insert_member_page", as: "insert_member"

	#delete member of a team
	patch "/dashboard/teams/:id/unsubscribe/:id_subscribe" => "member_teams#unsubscribe_member", as: "unsubscribe_member"

	#former members
	get "/dashboard/teams/:id/former_members/" => "member_teams#former_members", as: "former_members"

	devise_for :users
	resources :members, path: '/dashboard/members'
	resources :teams, path: '/dashboard/teams'
	resources :icm_events, path: '/dashboard/icm_events'
	resources :churches, path: '/dashboard/churches'
end

app/models/church.rb
class Church < ApplicationRecord
	has_many :members
end

app/controllers/churches_controller.rb
class ChurchesController < ApplicationController
  before_action :set_church, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /churches
  # GET /churches.json
  def index
    @churches = Church.all
    @title_section = "Igrejas"
    @title = @title_section
  end

  # GET /churches/1
  # GET /churches/1.json
  def show
    @title_section = @church.name
    @title = "Igreja: " + @title_section
    @members = @church.members
  end

  # GET /churches/new
  def new
    @church = Church.new
    @title_section = "Cadastro de Igreja"
    @title = @title_section
  end

  # GET /churches/1/edit
  def edit
    @title_section = "Editando: " + @church.name
    @title = @title_section
  end

  # POST /churches
  # POST /churches.json
  def create
    @church = Church.new(church_params)

    respond_to do |format|
      if @church.save
        format.html { redirect_to @church, notice: 'Church was successfully created.' }
        format.json { render :show, status: :created, location: @church }
      else
        format.html { render :new }
        format.json { render json: @church.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /churches/1
  # PATCH/PUT /churches/1.json
  def update
    respond_to do |format|
      if @church.update(church_params)
        format.html { redirect_to @church, notice: 'Church was successfully updated.' }
        format.json { render :show, status: :ok, location: @church }
      else
        format.html { render :edit }
        format.json { render json: @church.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /churches/1
  # DELETE /churches/1.json
  def destroy
    @church.destroy
    respond_to do |format|
      format.html { redirect_to churches_url, notice: 'Church was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_church
      @church = Church.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def church_params
      params.require(:church).permit(:name, :code, :address, :district, :city, :state, :number, :c_type, :zip)
    end
end

app/helpers/churches_helper.rb
module ChurchesHelper
end

app/views/churches/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
          Insira dos Dados Corretamente
      </div>                
      <div class="panel-body">
        <div class="row">
          <%= form_with(model: church, local: true) do |form| %>
            <% if church.errors.any? %>
              <div id="alert alert-danger alert-dismissable">
                <h2><%= pluralize(church.errors.count, "error") %> prohibited this church from being saved:</h2>

                <ul>
                <% church.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>

            <div class="col-lg-6">                                
              <div class="form-group">
                <%= form.label "Nome" %>
                <%= form.text_field :name, id: :church_name, class: "form-control", placeholder: "Insira o Nome" %>
              </div>                                
            </div> <!-- col-lg-6 -->
            <div class="col-lg-3">
              <div class="form-group">
                <%= form.label "Status" %>
                <%= form.text_field :c_type, id: :church_c_type, class: "form-control", placeholder: "Insira o Tipo" %>
              </div>
            </div> <!-- col-lg-3 -->
            <div class="col-lg-3">
              <div class="form-group">
                <%= form.label "Código" %>
                <%= form.text_field :code, id: :church_code, class: "form-control", placeholder: "Insira o Código" %>
              </div>
            </div> <!-- col-lg-3 -->

            <div class="col-lg-6">                                
              <div class="form-group">
                <%= form.label "Endereço" %>
                <%= form.text_field :address, id: :church_address, class: "form-control", placeholder: "Insira o Endereço" %>
              </div>                                
            </div> <!-- col-lg-6 -->
            <div class="col-lg-2">
              <div class="form-group">
                <%= form.label "Número" %>
                <%= form.text_field :number, id: :church_number, class: "form-control", placeholder: "Insira o Número" %>
              </div>
            </div> <!-- col-lg-2 -->
            <div class="col-lg-4">
              <div class="form-group">
                <%= form.label "Bairro" %>
                <%= form.text_field :district, id: :church_district, class: "form-control", placeholder: "Insira o Bairro" %>
              </div>
            </div> <!-- col-lg-4 -->

            <div class="col-lg-5">                                
              <div class="form-group">
                <%= form.label "Cidade" %>
                <%= form.text_field :city, id: :church_city, class: "form-control", placeholder: "Insira a Cidade" %>
              </div>                                
            </div> <!-- col-lg-5 -->
            <div class="col-lg-5">
              <div class="form-group">
                <%= form.label "Estado" %>
                <%= form.text_field :state, id: :church_state, class: "form-control", placeholder: "Insira o Estado" %>
              </div>
            </div> <!-- col-lg-5 -->
            <div class="col-lg-2">
              <div class="form-group">
                <%= form.label "CEP" %>
                <%= form.text_field :zip, id: :church_zip, class: "form-control", placeholder: "Insira o CEP" %>
              </div>
            </div> <!-- col-lg-2 -->

            <div class="col-lg-12">
              <%= form.submit "Finalizar", class: "btn btn-default" %>
              <%= link_to 'Voltar', churches_path, class: "btn btn-default" %>
            </div>
          <% end %>
          <%#= link_to 'Voltar', churches_path, class: "btn btn-default" %>
        </div> <!-- row -->
      </div> <!-- panel-body -->
    </div> <!-- panel panel-default -->
  </div> <!-- col-lg-12 -->
</div> <!-- row -->

app/views/churches/edit.html.erb
<%= render 'form', church: @church %>

app/views/churches/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
          Listagem
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
          <thead>
            <tr>
              <th>Nome</th>
              <th><center>Status</center></th>
              <th><center>Cidade</center></th>
              <th><center>Estado</center></th>
              <th><center>Ações</center></th>
            </tr>
          </thead>

          <tbody>
            <% @churches.each do |church| %>
              <tr class="odd gradeX">
                <td><%= church.name %></td>
                <td><center><%= church.c_type %></center></td>
                <td><center><%= church.city %></center></td>
                <td><center><%= church.state %></enter></td>
                <td>
                  <center>
                    <%= link_to 'Exibir', church %> |
                    <%= link_to 'Editar', edit_church_path(church) %> | 
                    <%= link_to 'Excluir', church, method: :delete, data: { confirm: 'Are you sure?' } %>
                  </center>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div><!-- /.panel-body -->      
    </div><!-- /.panel -->    
  </div><!-- /.col-lg-12 -->  
</div><!-- row -->
<%#= link_to 'New Church', new_church_path %>

app/views/churches/new.html.erb
<%= render 'form', church: @church %>

app/views/churches/show.html.erb
<div class="row">
  <div class="col-lg-5">
    <div class="panel panel-default">
      <div class="panel-heading">
        Dados Completos <%#Outros Dados%>
      </div>                
      <div class="panel-body">
        <div class="row">
          <% if (notice) %>
            <div class="col-lg-12">
              <div class="alert alert-success">
                <%= notice %>
              </div>            
            </div>
          <% end %>
          <div class="col-lg-12">
            <p> <b> Código:  </b> <%= @church.code %> </p>
            <p> <b> Status:  </b> <%= @church.c_type %> </p>
            <p> <b> Endereço:</b> <%= @church.address %> </p>
            <p> <b> Número:  </b> <%= @church.number %> </p>
            <p> <b> Bairro:  </b> <%= @church.district %> </p>
            <p> <b> Cidade:  </b> <%= @church.city %> </p>
            <p> <b> Estado:  </b> <%= @church.state %> </p>
            <p> <b> CEP:     </b> <%= @church.zip %> </p>

            <hr>

            <%= link_to 'Editar', edit_church_path(@church), class: "btn btn-default" %>
            <%= link_to 'Voltar', churches_path, class: "btn btn-default" %>
          </div> <!-- col-lg-12 -->
        </div> <!-- row -->
      </div> <!-- panel-body -->
    </div> <!-- panel panel-default -->
  </div> <!-- col-lg-5 -->

  <div class="col-lg-7">
    <div class="panel panel-default">
      <div class="panel-heading">
        Membros da Igreja
      </div> <!-- panel-heading -->
      <div class="panel-body">

        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
          <thead>
            <tr>
              <th>Nome</th>
              <th><center>Telefone</center></th>
              <!--th><center>Ações</center></-->
            </tr>
          </thead>

          <tbody>
          <% @members.each do |member| %>
            <tr>
              <td><%= member.name_abv %></td>
              <td><center><%= member.phone %></center></td>
              <!--td>
                <center>
                  <%#= link_to 'Show', member %>
                  <%#= link_to 'Edit', edit_member_path(member) %>
                  <%#= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %>
                </center>
              </td-->
            </tr>
          <% end %>
        </tbody>
      </table>

      </div> <!-- panel-body -->
    </div> <!-- panel panel-default -->
  </div> <!-- col-lg-7 -->

</div> <!-- row -->    