config/routes.rb
Rails.application.routes.draw do
	root "dashboard#index"

	get "dashboard" => "dashboard#index"
	get "index" => "dashboard#index"
	get "dashboard/index" => "dashboard#index"
	#get 'welcome/index'

	#insert member in a team
	post "/dashboard/teams/:id/insert_member/" => "member_teams#insert_member", as: "insert_member_team"
	get "/dashboard/teams/:id/insert_member/" => "member_teams#insert_member_page", as: "insert_member"

	#delete member of a team
	patch "/dashboard/teams/:id/unsubscribe/:id_subscribe" => "member_teams#unsubscribe_member", as: "unsubscribe_member"

	#former members
	get "/dashboard/teams/:id/former_members/" => "member_teams#former_members", as: "former_members"

	devise_for :users
	resources :members, path: '/dashboard/members'
	resources :teams, path: '/dashboard/teams'
	resources :icm_events, path: '/dashboard/icm_events'
	resources :churches, path: '/dashboard/churches'
end

app/models/member_team.rb
class MemberTeam < ApplicationRecord
	belongs_to :member, required: true
	belongs_to :team, required: true
end

app/controllers/member_teams_controller.rb
class MemberTeamsController < ApplicationController
	before_action :set_member_team, only: [:unsubscribe_member]
	before_action :set_former_members, only: [:former_members]
	before_action :set_team, only: [:former_members]
	before_action :authenticate_user!

	def insert_member_page
		@title = "Inserir Membro"
		@title_section = "Inserir Membro na Equipe"
		
		@members = Member.where.not({id: MemberTeam.select(:member_id).where(active: true)}).order(:name)
		@member_team = MemberTeam.new
	end

	def insert_member
		@mt = MemberTeam.new
			@mt.member_id = member_team_params[:member_id]
			@mt.team_id = params[:id]
			@mt.date_start = DateTime.now.to_date

		respond_to do |format|
			if @mt.save
				format.html { redirect_to team_path(params[:id]), notice: 'Membro Cadastrado com Sucesso' }
				#format.json { render :show, status: :created, location: @team }
			else
				format.html { redirect_to insert_member_path(params[:id]), notice: @mt.errors}
				#format.json { render json: @mt.errors, status: :unprocessable_entity }
			end
		end	
		#redirect_to team_path(params[:id])
	end

	def unsubscribe_member
		@mt.date_finish = DateTime.now.to_date
		@mt.active = false
		respond_to do |format|
			if @mt.save
				format.html { redirect_to team_path(params[:id]), notice: 'Vínculo Encerrado com Sucesso' }
				#format.json { render :show, status: :created, location: @team }
			else
				format.html { redirect_to team_path(params[:id]), notice: @mt.errors}
				#format.json { render json: @mt.errors, status: :unprocessable_entity }
			end
		end	
	end

	def former_members
		@title = "Membros Antigos: " + @team.name
		@title_section = @title
	end




	private
		def member_team_params
			params.require(:member_team).permit(:member_id)
		end

		def set_member_team
			@mt = MemberTeam.find(params[:id_subscribe])
		end

		def set_team
			@team = Team.find(params[:id])
		end

		def set_former_members
			@member_teams = MemberTeam.all.where('team_id = ? AND active = ?', params[:id], false)
		end
end

app/helpers/member_teams_helper.rb
module MemberTeamsHelper
end

app/views/member_teams/former_members.html.erb
<%#<p id="notice"><%= notice </p>%>
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
          Listagem
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
          <thead>
            <tr>
              <th>Nome</th>
              <th><center>Igreja</center></th>
              <th><center>Início</center></th>
              <th><center>Final</center></th>
            </tr>
          </thead>

          <tbody>
          <% @member_teams.each do |member_team| %>
            <tr>
              <td><%= member_team.member.name %></td>
              <td><center><%= member_team.member.church.name %></center></td>
              <td><center><%= member_team.date_start %></center></td>
              <td><center><%= member_team.date_finish %></center></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <hr>

      <%= link_to "Voltar", team_path(params[:id]), class: "btn btn-default" %>

      </div><!-- /.panel-body -->      
    </div><!-- /.panel -->    
  </div><!-- /.col-lg-12 -->  
</div><!-- row -->

app/views/member_teams/insert_member_page.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
          Selecione o Membro
      </div>                
      <div class="panel-body">
        <div class="row">
          <% if (notice) %>
            <div class="col-lg-12">
              <div class="alert alert-danger alert-dismissable">
                <%= notice %>
              </div>            
            </div>
          <% end %>
          <%= form_for @member_team, url: insert_member_team_path, method: :post do |form|%>
            <div class="col-lg-4">
              <div class="form-group">
                <%= form.label "Membros sem equipe" %> <br/>
                <%= form.collection_select(:member_id, @members, :id, :name, class: "form-control") %>
              </div>
            </div> <!-- col-lg-4 -->
        </div> <!-- row -->
        <hr>
        <div class="row">
          <div class="col-lg-12">
            <%= form.submit "Inserir", class: "btn btn-default" %>
            <%= link_to "Voltar", team_path(params[:id]), class: "btn btn-default" %>
          </div>
        </div>
          <% end %>
      </div> <!-- panel-body -->
    </div> <!-- panel panel-default -->
  </div> <!-- col-lg-12 -->
</div> <!-- row -->