config/routes.rb
Rails.application.routes.draw do
	root "dashboard#index"

	get "dashboard" => "dashboard#index"
	get "index" => "dashboard#index"
	get "dashboard/index" => "dashboard#index"
	#get 'welcome/index'

	#insert member in a team
	post "/dashboard/teams/:id/insert_member/" => "member_teams#insert_member", as: "insert_member_team"
	get "/dashboard/teams/:id/insert_member/" => "member_teams#insert_member_page", as: "insert_member"

	#delete member of a team
	patch "/dashboard/teams/:id/unsubscribe/:id_subscribe" => "member_teams#unsubscribe_member", as: "unsubscribe_member"

	#former members
	get "/dashboard/teams/:id/former_members/" => "member_teams#former_members", as: "former_members"

	devise_for :users
	resources :members, path: '/dashboard/members'
	resources :teams, path: '/dashboard/teams'
	resources :icm_events, path: '/dashboard/icm_events'
	resources :churches, path: '/dashboard/churches'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= @title %></title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= csrf_meta_tags %>

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap Core CSS -->
    <%= stylesheet_link_tag 'dashboard/vendor/bootstrap/css/bootstrap.min.css', 'data-turbolinks-track' => 'reload' %>

    <!-- MetisMenu CSS -->
    <%= stylesheet_link_tag 'dashboard/vendor/metisMenu/metisMenu.min.css', 'data-turbolinks-track' => 'reload' %>
    
    <!-- DataTables CSS -->
    <%= stylesheet_link_tag 'dashboard/vendor/datatables-plugins/dataTables.bootstrap.css', 'data-turbolinks-track' => 'reload' %>

    <!-- DataTables Responsive CSS -->
    <%= stylesheet_link_tag 'dashboard/vendor/datatables-responsive/dataTables.responsive.css', 'data-turbolinks-track' => 'reload' %>

    <!-- Custom CSS -->
    <%= stylesheet_link_tag 'dashboard/dist/css/sb-admin-2.css', 'data-turbolinks-track' => 'reload' %>

    <!-- Custom Fonts -->
    <%= stylesheet_link_tag 'dashboard/vendor/font-awesome/css/font-awesome.min.css', 'data-turbolinks-track' => 'reload' %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
  </head>

  <body>
    <% if user_signed_in? %>
    <div id="wrapper">

        

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "GERÊNCIA MAANAIM-RN", dashboard_path, class: "navbar-brand" %>
            </div>
            <!-- /.navbar-header -->

            <!--<ul class="nav navbar-top-links navbar-right">               
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> Meu Perfil </a>
                        </li>
                        <li><a href="#"><i class="fa fa-key fa-fw"></i> Alterar Senha </a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                     /.dropdown-user
                </li>
                <!-- /.dropdown
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <%= link_to dashboard_path do %>
                                <i class="fa fa-dashboard fa-fw"></i>
                                Painel de Controle
                            <% end %>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-building fa-fw"></i> Igrejas <span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <%= link_to 'Listagem', churches_path %>
                                </li>
                                <li>
                                    <%= link_to 'Cadastrar', new_church_path %>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-child fa-fw"></i>Membros<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <%= link_to 'Listagem', members_path %>
                                </li>
                                <li>
                                    <%= link_to 'Cadastrar', new_member_path %>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-cog fa-fw"></i>Equipes<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <%= link_to 'Listagem', teams_path %>
                                </li>
                                <li>
                                    <%= link_to 'Cadastrar', new_team_path %>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-calendar fa-fw"></i>Eventos<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <%= link_to 'Listagem', icm_events_path %>
                                </li>
                                <li>
                                    <%= link_to 'Cadastrar', new_icm_event_path %>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-key fa-fw"></i>Configurações Pessoais<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <!--li>
                                    <a href="#">Alterar Dados Pessoais</a>
                                </li>
                                <li>
                                    <a href="#">Alterar Senha</a>
                                </li-->
                                <li>
                                    <%= link_to "Sair", destroy_user_session_path, method: :delete %>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div> <!-- /.sidebar-collapse -->
            </div> <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12"> 
                        <h1 class="page-header"><%= @title_section %></h1>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>

    <% end %>


                    <%= yield %>


    <% if user_signed_in? %>
                </div><!-- /.container-fluid -->
            </div><!-- /#page-wrapper -->
        </div> <!-- /#wrapper -->
    <% end %>


	<!-- jQuery -->
	<%= javascript_include_tag 'dashboard/vendor/jquery/jquery.min', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap Core JavaScript -->
	<%= javascript_include_tag 'dashboard/vendor/bootstrap/js/bootstrap.min', 'data-turbolinks-track': 'reload' %>

    <!-- Metis Menu Plugin JavaScript -->
	<%= javascript_include_tag 'dashboard/vendor/metisMenu/metisMenu.min', 'data-turbolinks-track': 'reload' %>
    
    <!-- DataTables JavaScript -->
    <%= javascript_include_tag 'dashboard/vendor/datatables/js/jquery.dataTables.min', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'dashboard/vendor/datatables-plugins/dataTables.bootstrap.min', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'dashboard/vendor/datatables-responsive/dataTables.responsive', 'data-turbolinks-track': 'reload' %>

    <!-- Custom Theme JavaScript -->
	<%= javascript_include_tag 'dashboard/dist/js/sb-admin-2', 'data-turbolinks-track': 'reload' %>
    
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
    </script>
</body>

</html>